### ISSUE TITLE
Asset URL contains language code

### ISSUE THREAD

**Issue by MaTToX3** [ompmega/oc-mix-helper-plugin#1]
If you are using Mix Helper together with a RainLab.Translate and have option "Force URL schema" enabled, the path of CSS and JS will also include language code. A closer look into the source code reveals that the path is returned by usign Cms::url() helper, which is not really needed. 

Changing this line:

```
return Cms::url(
    sprintf('/themes/%s/assets', $theme->getDirName()) . $manifest[$path]
);
```

to this:

`return sprintf('/themes/%s/assets', $theme->getDirName()) . $manifest[$path];`

fixes the issue.

**Comment by drmzio** [comment]
Hi @MaTToX3 

Thanks for submitting this issue. I'll fix this on the next update.

**Comment by MaTToX3** [comment]
I can submit PR later today if you want.

**Comment by drmzio** [comment]
I sent out an update. It should be fixed now 👍
